on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# Setup GitHub Actions Runner 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1

# Configure AWS Credentials 
#
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

# Build
      - run: sam build --use-container

# Deploy in QA | Test
  deploy-test: 
    runs-on: ubuntu-latest
    environment: 'test'
    needs: build
    steps: 
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world-qa-test --s3-bucket  sam-helloworld-bucket --capabilities CAPABILITY_IAM --region ap-south-1

# Deploy in Prod
  deploy-prod: 
    runs-on: ubuntu-latest 
    environment: 'prod'
    needs: build
    steps: 
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world-prod --s3-bucket  sam-helloworld-bucket --capabilities CAPABILITY_IAM --region ap-south-1



